export const AUTH_REGISTER_USER = 'AUTH_REGISTER_USER';
export const AUTH_LOGIN_USER = 'AUTH_LOGIN_USER';
export const AUTH_RESET_PASSWORD = 'AUTH_RESET_PASSWORD';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';